### ISSUE TITLE
I want to implement features like input boxes in the game, how can I do that?

### ISSUE THREAD

**Issue by RoveAir** [jkatsanis/SpriteEngineUI#11]

**Comment by jkatsanis** [comment]
hello, im so sorry that i did not see the issue, i didnt think someone would actually use the engine lmao. You can create a input text field using ImGui since the engine does not have a build in UI feature kind of.

```C++
// Your C++ code here
static char buffer[256] = "";
ImGui::InputText("Enter Text", buffer, IM_ARRAYSIZE(buffer));
```
